server:
  port: 9093

spring:
  application:
    name: food-inventory-service
  profiles:
    active: '@spring.active.profile@'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8717/eureka/

services:
  restaurant-onboarding:
    url: "http://RESTAURANT-ONBOARDING-SERVICE"